name: MinigamePlugin
version: '4.0.0'
main: base.MinigamePlugin
api-version: '1.21'
commands:
  misc:
    description: Miscellaneous commands
    usage: /<command> <name> <...>
  minigame:
    description: Shows the minigame menu
    usage: /<command> <name>
  mg_disco_mayhem:
    description: Starts the Disco Mayhem minigame
    usage: /<command> <state>
  mg_blueprint_bazaar:
    description: Starts the Blueprint Bazaar minigame
    usage: /<command> <state>
  mg_hole_in_the_wall:
    description: Starts the Hole In The Wall minigame
    usage: /<command> <state>




  push_block:
    description: Pushes the block in a specified coordinate by a specified amount of blocks in a specified direction. The block will be pushed every specified interval by 1 block in ticks.
    usage: /<command> <x> <y> <z> <amount> <direction> <interval>
  give_diamonds:
    description: Gives the player 3 diamonds
    usage: /<command>